version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: tasks-postgres
    restart: always
    environment:
      POSTGRES_USER: tasks_user
      POSTGRES_PASSWORD: tasks_pass
      POSTGRES_DB: tasks_db
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: